package patterns

import "github.com/RA000WL/RavenRecon/internal/asset"

// cloudTable holds cloud-platform key shapes: Google (API keys and OAuth
// access tokens), Firebase, Azure storage connection strings, Cloudflare,
// DigitalOcean, and the deployment platforms (Vercel, Netlify, Railway) whose
// tokens have no stable public prefix and are therefore context-shaped.
func cloudTable() []Pattern {
	return []Pattern{
		{
			ID:        "google-api-key",
			Type:      asset.SecretTypeGoogle,
			Provider:  "google",
			Family:    FamilyStructured,
			Regex:     `AIza[0-9A-Za-z_-]{35}`,
			Strength:  0.9,
			MinLen:    39,
			MaxLen:    39,
			Negatives: []string{"EXAMPLE"},
			Hints:     []string{"google_api_key", "gcp_api_key", "browser_key"},
			Positives: []string{"google", "gcp", "firebase"},
		},
		{
			ID:        "google-oauth-access",
			Type:      asset.SecretTypeOAuth,
			Provider:  "google",
			Family:    FamilyStructured,
			Regex:     `ya29\.[0-9A-Za-z_-]{20,256}`,
			Strength:  0.75,
			MinLen:    26,
			MaxLen:    261,
			Hints:     []string{"access_token", "google_token"},
			Positives: []string{"google", "gcp"},
		},
		{
			ID:        "firebase-db-url",
			Type:      asset.SecretTypeFirebase,
			Provider:  "firebase",
			Family:    FamilyStructured,
			Regex:     `https?://[a-z0-9][a-z0-9-]{0,38}\.(?:firebaseio|firebaseapp)\.com(?:/[^\s"'<>]{0,256})?`,
			Strength:  0.45,
			MinLen:    20,
			MaxLen:    512,
			Hints:     []string{"firebase", "databaseurl"},
			Positives: []string{"firebase"},
		},
		{
			ID:        "azure-storage-connection",
			Type:      asset.SecretTypeAzure,
			Provider:  "azure",
			Family:    FamilyStructured,
			Regex:     `DefaultEndpointsProtocol=https;AccountName=[a-z0-9]{3,24};AccountKey=[A-Za-z0-9+/=]{60,200};`,
			Strength:  0.85,
			MinLen:    60,
			MaxLen:    400,
			Negatives: []string{"EXAMPLE"},
			Hints:     []string{"azure_storage_connection_string", "connection_string"},
			Positives: []string{"azure", "blob"},
		},
		{
			ID:        "cloudflare-api-token",
			Type:      asset.SecretTypeCloudflare,
			Provider:  "cloudflare",
			Family:    FamilyContextual,
			Regex:     `(?i)cloudflare[^;\n]{0,32}(?:api)?_?token\s*["']?\s*[:=]\s*["']?([A-Za-z0-9_-]{40})["']?`,
			Anchors:   []string{"cloudflare"},
			Group:     1,
			Strength:  0.8,
			MinLen:    40,
			MaxLen:    40,
			Entropy:   EntropyRule{MinShannon: 3.2, MinNormalized: 0.55, Class: ClassBase64URL},
			Hints:     []string{"cloudflare_api_token"},
			Positives: []string{"cloudflare"},
		},
		{
			ID:        "cloudflare-global-key",
			Type:      asset.SecretTypeCloudflare,
			Provider:  "cloudflare",
			Family:    FamilyContextual,
			Regex:     `(?i)cloudflare[^;\n]{0,32}(?:api)?_?key\s*["']?\s*[:=]\s*["']?([0-9a-f]{37})["']?`,
			Anchors:   []string{"cloudflare"},
			Group:     1,
			Strength:  0.8,
			MinLen:    37,
			MaxLen:    37,
			Validator: ValidatorHex,
			Entropy:   EntropyRule{MinShannon: 3.2, MinNormalized: 0.8, Class: ClassHex},
			Hints:     []string{"cloudflare_api_key"},
			Positives: []string{"cloudflare"},
		},
		{
			ID:        "digitalocean-pat",
			Type:      asset.SecretTypeDigitalOcean,
			Provider:  "digitalocean",
			Family:    FamilyStructured,
			Regex:     `dop_v1_[a-f0-9]{64}`,
			Strength:  0.9,
			MinLen:    71,
			MaxLen:    71,
			Validator: ValidatorHex,
			Hints:     []string{"digitalocean_token", "do_token"},
			Positives: []string{"digitalocean"},
		},
		{
			ID:        "digitalocean-oauth",
			Type:      asset.SecretTypeDigitalOcean,
			Provider:  "digitalocean",
			Family:    FamilyStructured,
			Regex:     `doo_v1_[a-f0-9]{64}`,
			Strength:  0.9,
			MinLen:    71,
			MaxLen:    71,
			Validator: ValidatorHex,
			Hints:     []string{"digitalocean_token"},
			Positives: []string{"digitalocean"},
		},
		{
			ID:        "vercel-token",
			Type:      asset.SecretTypeVercel,
			Provider:  "vercel",
			Family:    FamilyContextual,
			Regex:     `(?i)vercel[^;\n]{0,24}(?:auth )?token\s*["']?\s*[:=]\s*["']?([A-Za-z0-9_-]{20,64})["']?`,
			Anchors:   []string{"vercel"},
			Group:     1,
			Strength:  0.55,
			MinLen:    20,
			MaxLen:    64,
			Entropy:   EntropyRule{MinShannon: 3.0, MinNormalized: 0.5, Class: ClassBase64URL},
			Hints:     []string{"vercel_token"},
			Positives: []string{"vercel"},
		},
		{
			ID:        "netlify-token",
			Type:      asset.SecretTypeNetlify,
			Provider:  "netlify",
			Family:    FamilyContextual,
			Regex:     `(?i)netlify[^;\n]{0,24}token\s*["']?\s*[:=]\s*["']?([A-Za-z0-9_-]{20,64})["']?`,
			Anchors:   []string{"netlify"},
			Group:     1,
			Strength:  0.55,
			MinLen:    20,
			MaxLen:    64,
			Entropy:   EntropyRule{MinShannon: 3.0, MinNormalized: 0.5, Class: ClassBase64URL},
			Hints:     []string{"netlify_token"},
			Positives: []string{"netlify"},
		},
		{
			ID:        "railway-token",
			Type:      asset.SecretTypeRailway,
			Provider:  "railway",
			Family:    FamilyContextual,
			Regex:     `(?i)railway[^;\n]{0,24}token\s*["']?\s*[:=]\s*["']?([A-Za-z0-9_-]{20,64})["']?`,
			Anchors:   []string{"railway"},
			Group:     1,
			Strength:  0.55,
			MinLen:    20,
			MaxLen:    64,
			Entropy:   EntropyRule{MinShannon: 3.0, MinNormalized: 0.5, Class: ClassBase64URL},
			Hints:     []string{"railway_token"},
			Positives: []string{"railway"},
		},
	}
}
